name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # æ¯æ¬¡ push åˆ° main åˆ†æ”¯è§¦å‘

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # æ‹‰å–ä»£ç 
      - name: Checkout repository
        uses: actions/checkout@master

      - name: pnpm-setup
        uses: pnpm/action-setup@master
        with:
          version: 9.5.0

      # å®‰è£…ä¾èµ–
      - name: Install dependencies
        run: pnpm install

      # æ„å»ºé¡¹ç›®
      - name: Build
        run: pnpm build

      # éƒ¨ç½²åˆ° GitHub Pages
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: dist