name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # æ¯æ¬¡ push åˆ° master åˆ†æ”¯è§¦å‘

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # æ‹‰å–ä»£ç 
      - name: Checkout repository
        uses: actions/checkout@master

      - name: pnpm-setup
        uses: pnpm/action-setup@master
        with:
          version: 9.5.0

      # å®‰è£…ä¾èµ–
      - name: Install dependencies
        run: pnpm install

      # æ„å»ºé¡¹ç›®
      - name: Build
        run: pnpm build

            # ğŸ‘‰ Debug: åˆ—å‡ºæ„å»ºç»“æœ
      - name: List dist files
        run: |
          echo "==== dist ç›®å½•ç»“æ„ ===="
          ls -R dist
          echo "==== assets æ–‡ä»¶ ===="
          ls dist/assets || true

      # ğŸ‘‰ Debug: ä¸Šä¼ æ„å»ºäº§ç‰©ï¼Œæ–¹ä¾¿ä¸‹è½½æ£€æŸ¥
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist

      # éƒ¨ç½²åˆ° GitHub Pages
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: dist